[build]
  publish = "."
  command = "echo 'Build completed'"

[functions]
  directory = "netlify/functions"

# Redirección simple para la API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Headers básicos - SIN restricciones que puedan causar problemas
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
