# =============================================
# TECSITEL PERU E.I.R.L. - Configuración Netlify v4.0
# Corregida para un despliegue exitoso
# =============================================

[build]
  # El directorio 'publish' contiene los archivos a desplegar.
  # En este caso, el index.html está en la raíz.
  publish = "."
  
  # El comando de build no es necesario ya que Netlify
  # instalará las dependencias de las funciones automáticamente.
  command = "echo 'Build step not required. Netlify will handle function dependencies.'"
  
  # Directorio de las Netlify Functions.
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# =============================================
# CONFIGURACIÓN DE FUNCIONES
# =============================================
[functions]
  directory = "netlify/functions"
  # 'nft' (Netlify Function Tracer) es el bundler recomendado y por defecto.
  node_bundler = "nft"
  
  # Excluir 'pg-native' que puede causar problemas en el entorno de build de Linux.
  # La librería 'pg' usará la versión de JavaScript por defecto.
  [functions."*"]
    external_node_modules = ["pg-native"]

# =============================================
# REDIRECCIONES PARA LA API SERVERLESS
# =============================================
# Esta regla es crucial. Dirige todas las llamadas a /api/... 
# a tu función 'api.js' sin cambiar la URL en el navegador.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Regla 'catch-all' para aplicaciones de una sola página (SPA).
# Asegura que las rutas del lado del cliente funcionen correctamente.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =============================================
# HEADERS DE SEGURIDAD (Sin cambios)
# =============================================
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"


