# =============================================
# TECSITEL PERU E.I.R.L. - Configuración Netlify v4.0
# Archivo corregido sin errores de sintaxis
# =============================================

[build]
  publish = "."
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[functions]
  directory = "netlify/functions"

# =============================================
# REDIRECCIONES SIMPLIFICADAS
# =============================================

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =============================================
# HEADERS BÁSICOS
# =============================================

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"