# ========================================
# Tecsitel v4.0 - Configuración de Netlify
# ========================================

[build]
  # Directorio de archivos públicos
  publish = "."
  
  # Comando de construcción (no necesario para frontend estático)
  command = "echo 'Tecsitel v4.0 - Build completado'"

# ========================================
# Configuración de Functions
# ========================================
[functions]
  # Directorio donde están las functions
  directory = "netlify/functions"
  
  # Configuración específica para las functions
  node_bundler = "esbuild"
  
  # Variables de entorno específicas para functions
  [functions.environment]
    NODE_ENV = "production"

# ========================================
# Redirects y Rewrites
# ========================================

# Redirigir todas las rutas de API a la función principal
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Redirect para backward compatibility
[[redirects]]
  from = "/database/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Manejar rutas SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"]}

# ========================================
# Headers para seguridad
# ========================================
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad básica
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' https://i.imgur.com data:;
      font-src 'self';
      connect-src 'self' https://*.neon.tech;
      base-uri 'self';
      form-action 'self';
    '''
    
    # HSTS (solo para dominios con HTTPS)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    
    # Permisos específicos
    Permissions-Policy = '''
      camera=(),
      microphone=(),
      geolocation=(),
      payment=(),
      usb=()
    '''

# Headers específicos para la API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"

# Headers para archivos estáticos con caché
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ========================================
# Variables de entorno del sitio
# ========================================
[context.production.environment]
  NODE_ENV = "production"
  API_URL = "https://tecsitel.netlify.app/.netlify/functions/api"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  API_URL = "https://deploy-preview-{REVIEW_ID}--tecsitel.netlify.app/.netlify/functions/api"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  API_URL = "https://{BRANCH}--tecsitel.netlify.app/.netlify/functions/api"

# ========================================
# Configuración de Edge Functions (opcional)
# ========================================
[edge_functions]
  # Directorio para edge functions si las necesitas en el futuro
  directory = "netlify/edge-functions"

# ========================================
# Build plugins (opcional)
# ========================================
[[plugins]]
  package = "@netlify/plugin-essential-next-js"
  
  [plugins.inputs]
    # Configuración específica si necesitas plugins

# ========================================
# Configuración de desarrollo local
# ========================================
[dev]
  # Puerto para desarrollo local
  port = 8888
  
  # Comando para desarrollo local
  command = "echo 'Tecsitel v4.0 desarrollo local iniciado'"
  
  # Variables de entorno para desarrollo
  [dev.environment]
    NODE_ENV = "development"
    
# ========================================
# Configuración de formularios
# ========================================
[forms]
  # Habilitar formularios de Netlify si los necesitas
  spam_protection = true

# ========================================
# Configuración específica por rama
# ========================================

# Configuración para producción (rama main)
[context.production]
  # Variables específicas de producción se definen en la UI de Netlify
  
# Configuración para desarrollo (otras ramas)
[context.branch-deploy]
  # Variables para ramas de desarrollo

# ========================================
# Configuración de rendimiento
# ========================================

# Compresión automática
[processing]
  skip_processing = false

[processing.css]
  bundle = false
  minify = true

[processing.js]
  bundle = false
  minify = true

[processing.html]
  pretty_urls = true

[processing.images]
  compress = true

# ========================================
# Configuración de monitoreo y analytics
# ========================================

# Large Media (para archivos grandes)
[[plugins]]
  package = "netlify-plugin-large-media"
  
  [plugins.inputs]
    # Solo si necesitas manejar archivos grandes

# ========================================
# Configuración de notificaciones
# ========================================

# Notificaciones de deploy exitoso
[[notifications]]
  type = "email"
  event = "deploy-succeeded"
  email = "admin@tecsitel.com"

# Notificaciones de errores en deploy
[[notifications]]
  type = "email"
  event = "deploy-failed"
  email = "admin@tecsitel.com"

# ========================================
# Configuración de seguridad avanzada
# ========================================

# Rate limiting para la API (si Netlify lo soporta)
[[edge_functions]]
  function = "rate-limit"
  path = "/api/*"

# ========================================
# Configuración de dominios personalizados
# ========================================

# Si tienes un dominio personalizado, descomenta y configura:
# [[redirects]]
#   from = "https://tecsitel.com/*"
#   to = "https://www.tecsitel.com/:splat"
#   status = 301
#   force = true

# ========================================
# Configuración de logs y debugging
# ========================================

# Configuración para debugging en producción
[context.production.environment]
  NETLIFY_DEBUG = "false"
  
[context.deploy-preview.environment]
  NETLIFY_DEBUG = "true"

# ========================================
# Configuración de timeouts
# ========================================

# Timeout para functions (máximo 10 segundos en plan gratuito)
[functions]
  timeout = 10

# ========================================
# Configuración específica del proyecto
# ========================================

# Ignorar archivos en el deploy
[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- package.json package-lock.json"

# ========================================
# Comentarios de configuración
# ========================================

# Este archivo netlify.toml está optimizado para:
# 1. Tecsitel v4.0 con frontend estático
# 2. API en Netlify Functions
# 3. Base de datos PostgreSQL en Neon
# 4. Máxima seguridad y rendimiento
# 5. Fácil desarrollo y deploy

# Para configurar las variables de entorno secretas:
# 1. Ve a tu panel de Netlify
# 2. Site settings > Environment variables
# 3. Agrega las variables listadas en el archivo .env.example

# Para más información sobre configuración de Netlify:
# https://docs.netlify.com/configure-builds/file-based-configuration/